### ISSUE TITLE
'Getting error An error had occured with the ZAPI api call: "TypeError: Cannot read property 'forEach' of undefined ISSUE' while using this plugin

### ISSUE THREAD

**Issue by narora2** [vinicius-araujo/zephyr-protractor-reporter#1]
I am using this plugin to achieve integration of Protractor with Zephyr and to update execution results for a Zephyr test case with Protractor spec results as directed.

I have used the config options and the code provided on github for the same.

However, when I run the Protractor test, even though the reporter is initialized ('[12:34:59] I/direct - Using ChromeDriver directly...
initializing Zephyr reporter
Jasmine started)

I am getting the following error for the spec:-
An error had occured with the ZAPI api call: "TypeError: Cannot read property 'forEach' of undefined ISSUE = xxx'

Request for guidance to resolve this issue

**Comment by vinicius-araujo** [comment]
Hi, sorry for delay, this plugin is deprecated, but I'll try to help you anyway... looking at this message, it seems something is wrong with your issue on Jira.

1. Please make sure your issue type is a 'zephyt test' issue.
2. Please make sure your issue key is typed correctly after @ symbol.

**Comment by narora2** [comment]
Hi, sorry for the delayed response.
I see that you have closed it.
Yes, the issue type is a Zephyr test issue and the key has been typed after the @ symbol.
Can I please re-open this and send you my code to check for mistakes?

**Comment by vinicius-araujo** [comment]
Yes, sure, go ahead and send me.

**Comment by narora2** [comment]
Thanks for re-opening.
Do you have an email or should I paste the code here?

**Comment by vinicius-araujo** [comment]
vinisergio@gmail.com

**Comment by narora2** [comment]
Sent the code to the above email id.
